### ISSUE TITLE
what to do with csv files for practicals?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsdata#6]
There exists the .RData files, but most of the practicals read in `csv` files as that is what participants will do when it comes to their own data.

Practicals are set up assuming these `csv` files live in a directory `data` under their working directories.  Currently, I've placed them into the `inst/extdata` directory of the `dsdata` package; but that is inconsistent with the practicals.

Need to resolve this to avoid confusion on part of participants.

N.B. there is also a `figures` directory under the working directory to handle figures that are inserted into various practicals.  Said practicals will break if participants try to `knit` documents without the figures in the proper location.  The figures currently reside only in the OneDrive location.  Suggestions?

**Comment by lenthomas** [comment]
Reading through the discussion here, I assume this has now been fixed, so I'll close.
