### ISSUE TITLE
Search time field incorrect for wren3 (wren_cuecount)

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsdata#8]
You'll be thrilled to know that search time is 5 minutes * 2 visits = 10.  Somehow the field has become 20 (5 doubled, then doubled again).

**Comment by erex** [comment]
Incorrect effort aside, I cannot now duplicate the winter wren density estimate from cue counts of Buckland (2006):

![image](https://user-images.githubusercontent.com/330744/67392090-d1c92d00-f597-11e9-95eb-5c38a0696f2d.png)

that I was able to duplicate back in August for the workshop:
![image](https://user-images.githubusercontent.com/330744/67392139-ec9ba180-f597-11e9-9d6b-b6b887baa483.png)

when using this code:

```
library(dsdata)
data(wren_cuecount)
head(wren_cuecount)
hist(wren_cuecount$distance, xlab="Distance (m)", 
     main="Winter wren song detection distances")
library(Distance)
conversion.factor <- convert_units("meter", NULL, "hectare")
wren_cuecount$Effort <- 10 # wren_cuecount$Search.time
wrensong.hr <- ds(wren_cuecount, transect="point", key="hr", adjustment=NULL,
                  truncation=100)
cutpoints <- c(0,5,10,15,20,30,40,50,65,80,100)
plot(wrensong.hr, breaks=cutpoints, pdf=TRUE)
cuerate <- unique(wren_cuecount[ , c("Cue.rate","Cue.rate.SE")])
names(cuerate) <- c("rate", "SE")
(mult <- list(creation=cuerate))
wren.estimate <- dht2(wrensong.hr, flatfile=wren_cuecount, strat_formula=~1,
                      multipliers=mult, convert_units=conversion.factor)
print(wren.estimate, report="density")
```

**Comment by erex** [comment]
Feels like its a conversion factor problem because dividing the estimates by 10000 put them into the sensible range.

But the covered area values make no sense.

**Comment by dill** [comment]
Fixing the search time, I get:

```
> print(wren.estimate, report="density")
Summary statistics:
 .Label Area CoveredArea Effort   n  k    ER se.ER cv.ER
  Total 33.2     1005.31    320 771 32 2.409 0.236 0.098

Density estimates:
 .Label Estimate    se    cv    LCI    UCI      df
  Total   1.2018 0.238 0.198 0.8173 1.7674 520.656

Component percentages of variance:
 .Label Detection    ER Multipliers
  Total      4.82 24.38       70.79
```

**Comment by erex** [comment]
I confirm re-run of Montrave cue count with the revised `dsdata` produces the estimates you show above.
